- name: Deploy updated application
  hosts: nodejs_group
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Assuming Python path is consistent
    app_path: /usr/src/app                        # Application path from existing tasks
    image_name: my-nodejs-app                     # Image name from existing tasks
    image_tag: latest                             # Tag for the Docker image
    git_repo: https://github.com/carlosmsanchezm/RFTM-1-TEST.git             # Git repository URL
    git_version: main                             # Branch to pull from

  tasks:
    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present

    - name: Ensure the application directory exists
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory

    - name: Stop existing Docker container
      community.docker.docker_container:
        name: "{{ image_name }}"
        state: absent

    - name: Pull latest code from Git
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ app_path }}"
        version: "{{ git_version }}"
        force: yes

    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: "{{ app_path }}"
          nocache: true
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build

    - name: Start Docker container
      community.docker.docker_container:
        name: "{{ image_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "80:3000"
        recreate: true
        restart_policy: always

