- name: Deploy updated application
  hosts: nodejs_group
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_path: /usr/src/app
    image_name: my-nodejs-app
    image_tag: latest
    git_repo: https://github.com/carlosmsanchezm/RFTM-1-TEST.git
    git_version: main

  tasks:
    - name: Fetch all branches from Git
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ app_path }}"
        version: "{{ git_version }}"
        force: yes

    - name: Reset working directory to latest commit
      ansible.builtin.command:
        cmd: git reset --hard origin/{{ git_version }}
        chdir: "{{ app_path }}"

    - name: Build Docker image (with no cache)
      community.docker.docker_image:
        build:
          path: "{{ app_path }}"
          nocache: true
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build

    - name: Remove existing Docker container
      community.docker.docker_container:
        name: "{{ image_name }}"
        state: absent

    - name: Start Docker container with new image
      community.docker.docker_container:
        name: "{{ image_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "80:3000"
        recreate: true
        restart_policy: always

